### ISSUE TITLE
DdrWriter.cpp - wrong keywords for RGB at line 101 and 104 ?

### ISSUE THREAD

**Issue by dschaga** [KimuraRyo/libbsdf#10]
hi,
we are using Inspirer and your wonderfull Viewer which let us convert many measurements.
There is only one problem if we output to *.ddr and use it in Inspirer.
it gives us an error about a wrong keyword.
We then replace in the ddr file the reywords "gre" to "green" and "blu" to "blue" ..and then everything is working.

i'm new to github and don't want to make something wrong, so you may want to verify this bug(?) and may fix it.

**Comment by KimuraRyo** [comment]
Hi,

Thank you for reporting the error. Source code and binary with improved keywords are committed. Please check them. I confirmed keywords of the RGB mode with Integra. They answered that "green" and "blue" are better.
