### ISSUE TITLE
release tagging

### ISSUE THREAD

**Issue by mkae** [KimuraRyo/libbsdf#4]
Can you add release tags to your repo?!

So future ports or packages could easily learn from the repo which releases exist and thus allow for semi-automatic release version checks.

**Comment by KimuraRyo** [comment]
Yes, I can. I will do that at the next release.
Thank you for your advice.

**Comment by mkae** [comment]
Could you tag this repo's current state as well, please?

**Comment by mkae** [comment]
Thanks for having done the tagging.
